#!/usr/bin/env python3
"""One-shot migration: split wiki/participants/ into three people layers.

  participants/  — seminar fellows (role: participant) + visitors (role: visitor)
  mentors/       — role: mentor + role: external-speaker
  team/          — event-team + ops/volunteer/lead/job-title roles (role -> event-team)

Moves the page files, then rewrites EVERY person cross-link across wiki/ to the
correct relative path from each file's new location, and regenerates
participants/index.md + team/index.md. mentors/index.md and matchmaker.md keep
their curated prose (only their links get rewritten by the walk).

wiki/log.md is append-only history and is NOT relinked.

Dry-run by default. Pass --apply to actually move/write.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

WIKI = Path("/root/affine-interviewer/wiki")
PDIR = WIKI / "participants"
APPLY = "--apply" in sys.argv

SKIP_NAMES = {"index.md", "auto-match-review.md"}
PERSON_DIRS = ("participants", "mentors", "team")


def role_of(md: str) -> str:
    m = re.search(r"^role:\s*(.+?)\s*$", md, re.M)
    return (m.group(1).strip() if m else "participant")


# 1) slug -> target dir + canonical role, from CURRENT participants/*.md
loc: dict[str, str] = {}
norm_role: dict[str, str] = {}
for f in sorted(PDIR.glob("*.md")):
    if f.name in SKIP_NAMES:
        continue
    r = role_of(f.read_text(encoding="utf-8"))
    s = f.stem
    if r in ("mentor", "external-speaker"):
        loc[s], norm_role[s] = "mentors", r
    elif r in ("participant", "visitor"):
        loc[s], norm_role[s] = "participants", r
    else:
        loc[s], norm_role[s] = "team", "event-team"

people = set(loc)
moved = {s: d for s, d in loc.items() if d != "participants"}


def file_layer(p: Path) -> str:
    rel = p.relative_to(WIKI)
    return "root" if len(rel.parts) == 1 else rel.parts[0]


def rel_link(from_layer: str, slug: str) -> str:
    tgt = loc[slug]
    if from_layer == "root":
        return f"{tgt}/{slug}.md"
    if from_layer == tgt:
        return f"{slug}.md"
    return f"../{tgt}/{slug}.md"


LINK_RE = re.compile(r"\]\(([^)]+?)\)")
PERSON_PATH_RE = re.compile(r"(^|/)(participants|mentors|team)/[^/]+\.md$")


def rewrite(p: Path, txt: str) -> tuple[str, int]:
    fl = file_layer(p)
    in_person_dir = fl in PERSON_DIRS
    n = 0

    def repl(m: re.Match) -> str:
        nonlocal n
        target = m.group(1)
        path = target.split("#")[0].strip()
        if not path.endswith(".md"):
            return m.group(0)
        base = path.rsplit("/", 1)[-1][:-3]
        if base not in people:
            return m.group(0)
        is_person = bool(PERSON_PATH_RE.search(path)) or ("/" not in path and in_person_dir)
        if not is_person:
            return m.group(0)
        new = "](" + rel_link(fl, base) + ")"
        if new != m.group(0):
            n += 1
        return new

    return LINK_RE.sub(repl, txt), n


def main() -> None:
    print(f"{'APPLY' if APPLY else 'DRY-RUN'} — split people layers\n")
    print(f"mentors/  ({sum(1 for v in loc.values() if v=='mentors')}): "
          + ", ".join(sorted(s for s in loc if loc[s] == "mentors")))
    print(f"team/     ({sum(1 for v in loc.values() if v=='team')}): "
          + ", ".join(sorted(s for s in loc if loc[s] == "team")))
    print(f"participants/ stays ({sum(1 for v in loc.values() if v=='participants')})\n")

    # 2) move files (apply only)
    if APPLY:
        for s, d in moved.items():
            (WIKI / d).mkdir(parents=True, exist_ok=True)
            (PDIR / f"{s}.md").rename(WIKI / d / f"{s}.md")

    # 3) walk + relink every md except log.md (append-only history).
    #    Indexes ARE relinked here so no link breaks in the interim; the
    #    canonical three indexes are regenerated by the durable builder next.
    total_files, total_links = 0, 0
    for p in sorted(WIKI.rglob("*.md")):
        if p.name == "log.md":
            continue
        src = p
        # in dry-run moved files are still under participants/; project their
        # effective layer as the destination so counts are realistic
        if not APPLY and p.parent == PDIR and p.stem in moved:
            eff = WIKI / moved[p.stem] / p.name
        else:
            eff = p
        txt = src.read_text(encoding="utf-8")
        new, n = rewrite(eff, txt)
        if n:
            total_files += 1
            total_links += n
            if APPLY:
                src.write_text(new, encoding="utf-8")
    print(f"relink: {total_links} links across {total_files} files"
          + ("" if APPLY else " (projected)"))

    # 4) normalize role: on team pages (job-title -> event-team)
    if APPLY:
        for s, d in moved.items():
            if d == "team":
                fp = WIKI / "team" / f"{s}.md"
                t = fp.read_text(encoding="utf-8")
                t2 = re.sub(r"^role:\s*.+$", "role: event-team", t, count=1, flags=re.M)
                if t2 != t:
                    fp.write_text(t2, encoding="utf-8")

    print("done." if APPLY else "dry-run only — no files changed.")


if __name__ == "__main__":
    main()
