"""
Regenerate wiki/index.md from the current set of pages.

Reads frontmatter from each page in wiki/ to build a content-oriented catalog,
grouped by `type:`. The index is regenerated, not appended to.
"""
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
WIKI = REPO / "wiki"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)
TITLE_RE = re.compile(r"^title:\s*(.+)$", re.MULTILINE)
TYPE_RE = re.compile(r"^type:\s*(.+)$", re.MULTILINE)


def extract_meta(path):
    text = path.read_text(encoding="utf-8")
    m = FRONTMATTER_RE.match(text)
    if not m:
        return None, None, None
    front = m.group(1)
    t = TITLE_RE.search(front)
    ty = TYPE_RE.search(front)
    title = t.group(1).strip().strip("'\"") if t else None
    type_ = ty.group(1).strip() if ty else None

    # First non-frontmatter, non-heading paragraph = one-line summary
    body = text[m.end():].strip()
    summary = ""
    for line in body.split("\n"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("> "):
            line = line[2:]
        # strip markdown emphasis
        line = re.sub(r"[*_`]", "", line)
        summary = line[:140]
        break
    return title, type_, summary


GROUP_ORDER = [
    ("overview", "Overview"),
    ("principle", "Principles"),
    ("concept", "Concepts"),
    ("project", "Projects"),
    ("writing", "Writings"),
    ("theme", "Themes (synthesis pages)"),
    ("channel", "Channels"),
    ("member", "Members"),
    ("source", "Sources"),
]


def main():
    pages_by_type = {k: [] for k, _ in GROUP_ORDER}
    other = []

    for p in sorted(WIKI.rglob("*.md")):
        if p.name == "index.md" or p.name == "log.md":
            continue
        rel = p.relative_to(WIKI).as_posix()
        title, type_, summary = extract_meta(p)
        entry = (rel, title or rel, summary)
        if type_ in pages_by_type:
            pages_by_type[type_].append(entry)
        else:
            other.append(entry)

    out = []
    out.append("---")
    out.append("title: Index")
    out.append("type: meta")
    out.append("last_updated: 2026-05-08")
    out.append("---\n")
    out.append("# Index\n")
    out.append(
        "Content catalog for the wiki. Each entry: a relative path, a title, and a one-line summary. "
        "Generated by `build_wiki/build_index.py`. Edit by re-running, not by hand.\n"
    )

    for key, label in GROUP_ORDER:
        entries = sorted(pages_by_type[key])
        if not entries:
            continue
        out.append(f"\n## {label} ({len(entries)})\n")
        for rel, title, summary in entries:
            line = f"- [{title}](./{rel})"
            if summary:
                line += f" — {summary}"
            out.append(line)

    if other:
        out.append("\n## Other\n")
        for rel, title, summary in sorted(other):
            out.append(f"- [{title}](./{rel})")

    out_path = WIKI / "index.md"
    out_path.write_text("\n".join(out) + "\n", encoding="utf-8")
    total = sum(len(v) for v in pages_by_type.values()) + len(other)
    print(f"wrote index covering {total} pages")


if __name__ == "__main__":
    main()
